name: Install system dependencies
description: Installs system dependencies in the environment
runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang libclang-dev libssl-dev pkg-config
      shell: bash
