name: Install risc0
description: Installs risc0 in the environment
runs:
  using: "composite"
  steps:
    - name: Install risc0
      run: |
        curl -L https://risczero.com/install | bash
        /home/runner/.risc0/bin/rzup install
      shell: bash
